name: RandomCart
version: '${project.version}'
main: org.stupidcraft.randomcart.RandomCart
api-version: 1.13
folia-supported: true
authors: [ Triassic ]
description: Summons a Minecart randomly with loot inside of it when a block is broken.
