metadata.format.version = "1.1"

[versions]
bstats = "3.0.2"
paperlib = "1.0.8"
plugin-yml = "0.6.0"
spigot = "1.21-R0.1-SNAPSHOT"
shadow = "8.1.1"

[plugins]
pluginyml-bukkit = { id = "net.minecrell.plugin-yml.bukkit", version.ref = "plugin-yml" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[libraries]
bstats-bukkit = { group = "org.bstats", name = "bstats-bukkit", version.ref = "bstats" }
paperlib = { group = "io.papermc", name = "paperlib", version.ref = "paperlib" }
spigot-api = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
