name: Build

on: [ workflow_dispatch, pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew shadowJar --stacktrace --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: randomcart-artifacts
          path: build/libs/*.jar
          compression-level: 0